### ISSUE TITLE
Can I adopt your ghc.io domain for a similar service?

### ISSUE THREAD

**Issue by chrisdone** [dterei/GhciOnline#3]
Hey @dterei 

I authored and run tryhaskell.org. You can see it on my keybase: https://keybase.io/chrisdone which includes this github account and my tryhaskell.org domain.

And I'm currently working on an interpreter for GHC STG (https://github.com/chrisdone/prana) and once I'm able to interpret basic primops (ints, chars, integers) and pure code, I'm planning on making a web service that accepts a Haskell file as input, parses it with GHC's parser, whitelists imports and extensions (for safety reasons), and then compiles it to prana's bytecode format, and sends the bytecode back.

Prana will have its own interpreter (to run commandline), but I also want to implement a corresponding in-browser JS-based interpreter of the bytecode too (as a [byte array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Typed_arrays)). So that would be a great service to back a rewrite of tryhaskell and/or other educational tools (such as CodeWorld) that need to run Haskell, but it can be run in the browser, offloading CPU work to the user. 

I think `ghc.io` would be a super sweet domain for such a service, input GHC Haskell, receive bytecode. I saw that you were using it for a similar service but that it's no longer pointing to an active machine, and expires in 5 months. If you don't have any future plans for it, I'd love to adopt it.

I could wait 5 months and register it once it expires (presumably you weren't going to re-reg), but I didn't want to snatch it up without explicitly asking. This way there would be a transition process.

If you're happy to pass it over, my username on namecheap.com is `chrisdone` with email `namecheap@chrisdone.com`.

Thanks in any case!

**Comment by dterei** [comment]
Hey Chris,

Sorry but at this time I'd prefer to hold on to it. If that changes, I'll
let you know and make sure to transfer it over. But for now, I'd like to
eventually make use of it again once I get some time.

Cheers,
David

**Comment by chrisdone** [comment]
Thanks David! I’ll have to think of another name. 🤔

**Comment by dterei** [comment]
Chris - are you still interested in the ghc.io domain? I've not made use of it, so best it go to a good home. Let me know and I'll transfer it, otherwise my ownership will expire in about 2 weeks.

**Comment by chrisdone** [comment]
Hi @dterei - it's very nice of you to reach out to me again on this. 

Since we last spoke my GHC STG interpreter project is on indefinite hiatus, so I don't have a need for this domain anymore. I'm switching to implementing a Haskell service based on [my Duet](https://chrisdone.com/toys/duet-delta/) implementation, so it's not really "GHC" as such.

If you are planning on letting it expire anyway, I will happily take over just to keep the renewal up, to avoid domain squatters putting garbage on it, as e.g. GHC HQ or other Haskeller might want it in future for a useful project.

**Comment by dterei** [comment]
Ah OK, in that case i'll just renew it myself
